### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by ackxolotl** [dieliste/mensa#1]
There is no favicon yet :(

**Comment by chstdu** [comment]
One of these maybe? https://commons.wikimedia.org/wiki/Category:Cutlery_icons

**Comment by ackxolotl** [comment]
Yeah, why not :)

[This one](https://commons.wikimedia.org/wiki/File:RM-050_Food_sign.png) would fit to "Die LISTE" but I guess you won't see much of the cutlery at 16x16. So [that one](https://commons.wikimedia.org/wiki/File:AB-Rast.svg) is probably better?
