### ISSUE TITLE
How does aggregation API work

### ISSUE THREAD

**Issue by BastianHofmann** [dieliste/mensa#2]
Hello,

could you please explain how the http://graphite-kom.srv.lrz.de/render endpoint works and what the semantics of the returned data is?

Thank you!

**Comment by roflmaostc** [comment]
Sorry, out of my field of expertise @schaeffm

**Comment by ackxolotl** [comment]
@BastianHofmann This is a simple [Graphite endpoint](https://graphite-api.readthedocs.io/en/latest/api.html#the-render-api-render). Have a look at the graphs (and their URLs) at http://wlan.lrz.de/apstat/filter/Unterbezirk/mg/ to get a better understanding of the API.
