### ISSUE TITLE
Possibilities to integrate with TUM.sexy

### ISSUE THREAD

**Issue by mammuth** [dieliste/mensa#4]
Hi there,

[TUM.sexy](https://github.com/mammuth/TUM.sexy) provides redirects to TUM-related sites and other features like Speisepläne (https://hunger.tum.sexy).

Maybe it would be cool to somehow integrate this nice app into TUM.sexy?

Options
- Redirect mensa.tum.sexy -> mensa.liste.party (lame)
- Visually integrate your barometer into hunger.tum.sexy (cool)

What do you think about option 2?

Edit: I also created a high fidelity mockup: 
![OnPaste 20191126-140536](https://user-images.githubusercontent.com/3121306/69635966-ddf05080-1055-11ea-927c-49328098f427.png)

**Comment by ackxolotl** [comment]
Hey, sounds good! How would you integrate this into tum.sexy? tum.sexy seems to be written in PHP, and there should be a way to synchronize the WiFi stats in the back to not slow down the front page.

**Comment by mammuth** [comment]
Since you already have the styling for the barometer we could add a view here which renders it isolated. This could then be integrated via an iframe in tum.sexy. we could also generate an image out of the template and embed the barometer as an image.

**Comment by ackxolotl** [comment]
What do you think about including [this view](https://mensa.liste.party/minimal/)?

**Comment by ackxolotl** [comment]
I've just localized the homometer, depending on what your browser sends as `Accept-Language` header the page will be in English or German.

**Comment by ackxolotl** [comment]
> What do you think about including [this view](https://mensa.liste.party/minimal/)?

Doesn't look too bad :)

![mockup](https://user-images.githubusercontent.com/39318299/69812509-8f2aee00-11f0-11ea-80f3-5786f3697d5f.png)

**Comment by mammuth** [comment]
Awesome, we'll integrate it there! 🎉
