### ISSUE TITLE
Provide data additionally via an API

### ISSUE THREAD

**Issue by Philipp000** [dieliste/mensa#7]
I would like to integrate the mensa stats into the TUM Campus App.
Therefore, it would be ideal to have an API endpoint, instead of crawling the webpage.

What do you think about that? I can also look into this.

**Comment by ackxolotl** [comment]
Sure, feel free to submit a pull request! But did you notice that all data is aggregated from LRZ's graphite endpoint?

https://github.com/dieliste/mensa/blob/461186a590643ac796b8bb9e197e28ecb7b84fc9/crawler.py#L13-L14

**Comment by Philipp000** [comment]
I saw that, but I think, it would be still convenient, to have the aggregation done here, so that it's ready for use in other applications.

**Comment by ackxolotl** [comment]
The new version is online: https://mensa.liste.party/api/
